file_format: "1"
id: xiao_flex_v2
name: xiao_flex_v2
type: shield
url: https://github.com/WainingForests/zmk-xiao-flex-v2
requires: [seeed_xiao]
features:
  - keys
siblings:
  - xiao_flex_v2_left
  - xiao_flex_v2_right
  - xiao_flex_v2_dongle
